version: '3.8'

services:
 postgres:
    image: postgres:latest
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: krane_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

 goapp:
    build: .
    container_name: goapp_container
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: postgres://username:password@postgres:5432/krane_db?sslmode=disable
    volumes:
      - .:/app

volumes:
 postgres_data:
